### ISSUE TITLE
Note Content Not Wrapping After Grouping

### ISSUE THREAD

**Issue by sawmkw** [matt-flaig/Boomi-Platform-Extension#30]
Here is what it looks like
![image](https://github.com/mitchelljfranklin/Boomi-Platform-Extension/assets/3371906/38ee13a8-2616-4214-98d0-7b6454e0dd65)
But hovering over the note icon does this:
![image](https://github.com/mitchelljfranklin/Boomi-Platform-Extension/assets/3371906/302dc62c-5aea-4022-8256-f35bfb6f4487)

**Comment by matt-flaig** [comment]
Thanks for the report and screenshot! I've fixed this issue and it will be released in the next build of the extension. 👍
