### ISSUE TITLE
Legacy Shapes stopped working

### ISSUE THREAD

**Issue by MoranVashdi** [matt-flaig/Boomi-Platform-Extension#31]
boomi probably disabled this option for the add-on

Google Chrome
Chrome is up to date
Version 127.0.6533.73 (Official Build) (64-bit)

Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/127.0.0.0 Safari/537.36

**Comment by matt-flaig** [comment]
Thanks for your report. Looks like Chrome is doing a trial of deprecating `DOMNodeInserted` and we use that to detect the shapes.[ I've pushed a change ](https://github.com/mitchelljfranklin/Boomi-Platform-Extension/commit/768309896d0fab4dbb231cf5ab8084622c7d59e4) which will fix this issue and will reach out to the maintainer of the repository to see if they can update the extension on the Chrome, Firefox and Edge stores.

**Comment by sawmkw** [comment]
I wished I could say it's working again but sadly it is not.

**Comment by matt-flaig** [comment]
Hi @sawmkw, still working to submit the updated extension to the Chrome and Firefox Extension stores. Hopefully will have it updated today and then it will take a day or two to pass through their review system.

**Comment by sawmkw** [comment]
Thanks Matt!  Appreciate the update and apologize for sounding impatient.

*SAW*

*"All the money in the world has never bought one second of time."  --
Howard Stark*

**Comment by matt-flaig** [comment]
The release with the fix should now be live on Firefox and Chrome. 👍
